version: '3.8'

services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: pass123
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - auth-network

volumes:
  pg_data:

networks:
  auth-nework:
    driver: bridge