version: "3"

services:
  db:
    image:  postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - anime-network

volumes:
  pg_data:

networks:
  anime-network:
    driver: bridge